### ISSUE TITLE
Conditional Attributes in Resources

### ISSUE THREAD

**Issue by ram-noovosoft** [ram-noovosoft/mini-crm#2]
CompanyResource is defined as follows:
```
        return [
            'name' => $this->name,
            'email' => $this->email,
            'website' => $this->website,
            'number_of_employees' => $this->employees()->count(),
            'employees' => $this->whenLoaded('employees'),
            'created_at' => $this->whenLoaded('employees', $this->created_at),
        ];
```
**Question**: ([relevant commit](https://github.com/ram-noovosoft/mini-crm/commit/10d9ced4d365d82954c287bbe77f941101684a10))
- How to make sure that `number_of_employees` is not passed when creating a company?
Because when a new company is created, it is always 0, so there is no point in passing it to the response.
- But it should be passed in `list`, and `read` and `update` methods.

**Comment by sagar-noovosoft** [comment]
That's fine, we can still have `number_of_employees` in response even if it's 0.

Although to achieve this you can do following,
```
'number_of_employees' => $this->when(
    $this->employees()->count() != 0,
    $this->employees()->count(),
),
```

Now if you check telescope it produce N+1 issue (at least in list API for sure),

Read from following link and comment here what we can use here and what to modify in your code.
https://laravel.com/docs/7.x/eloquent-relationships#counting-related-models

Check Relationships section in following documentation link and make sure you're using it correctly,
https://laravel.com/docs/7.x/eloquent-resources#writing-resources

**Comment by ram-noovosoft** [comment]
Made the following changes:

In CompanyController
```
$companies = Company::withCount('employees')->paginate(25);
```

In CompanyResource:
```
'number_of_employees' => $this->employees_count,
```

I think, it's better if we return `number_of_employees` even if it is 0.
Because then when reading companies with no employees, at the moment, will not return that field at all

**Comment by sagar-noovosoft** [comment]
@ram-noovosoft Great, is this more cleaner now? did you checked telescope?

**Comment by sagar-noovosoft** [comment]
I would return `number_of_employees` always, no harm in returning 0.

**Just for note:** If you don't want to pass it then you can simply do following,
```
'number_of_employees' => $this->when(
    $this->employees_count !== null,
    (bool) $this->employees_count,
),
```

**Comment by ram-noovosoft** [comment]
yes I checked telescope and there was infact the N+1 query problem in the List API because of the way I was counting `number_of_employees` before.
